GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJub3ZpbiIsImRpc3BsYXlfbmFtZSI6Ik5vdmluIEFyZGlhbiBZdWxpYW50byIsImVtYWlsIjoibm92aW5Ac29sb21vbi5pZCIsInJvbGVJZCI6MSwiZGl2aXNpb25JZCI6MSwiY3JlYXRlZEF0IjoiMjAyNC0wMy0yMVQwODozMzowNy40MTFaIiwidXBkYXRlZEF0IjoiMjAyNC0wMy0yMVQwODozMzowNy40MTFaIiwiaWF0IjoxNzExMDEyMDk3LCJleHAiOjE3MTEwMTU2OTd9.g7tGd1HWO3JtnQtuDEA3HcH1QDKNK1eQGyodirLBxns

### GET USERS
GET http://localhost:3000/api/users/3

### POST USERS
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "novin",
  "display_name": "Novin Ardian Yulianto",
  "email": "novin@solomon.id",
  "password": "novinnovin",
  "role_id": 1,
  "division_id": 1
}

###
GET http://localhost:3000/api/division


###
GET http://localhost:3000/api/division/

### POST DIVISION
POST http://localhost:3000/api/division
Content-Type: application/json

{
  "name": "Human Resource"
}

### POST ROLE
POST http://localhost:3000/api/role
Content-Type: application/json

{
  "name": "USER"
}


### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "novin@solomon.id",
  "password": "novinnovin"
}
